---
- name: Get networking information for managed hosts
  hosts: all
  tasks:
    - name: Display IPv4 address
      debug:
        msg: "The IPv4 address for host {{ ansible_facts['hostname'] }} is: {{ ansible_facts['default_ipv4']['address'] }}"
